# Basic
name:               "CySoc Lab"
title:              "CySoc Lab"
description:        "The CySoc Lab is a cybercrime and social computing research group run by Dr. Hridoy Sankar Dutta."


# URL
url:                cysoclab.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "tools"
    href:           "/tools"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
